---

name: esmvaltool
channels:
  - conda-forge

dependencies:
  # Python packages that cannot be installed from PyPI:
  # TODO when switching to iris 2.x, switch straight to 2.2.0
  - iris=1.13
#  - iris=2.2.0
  - matplotlib<3
  - python-stratify
  - esmpy
  # Multi language support:
  - ncl
  - ncurses>5
  # TODO: add R, julia

  - pip:
      # TODO: include dummydata in esmvaltool repository and move to setup.py
      # dummydata fetched from github as a zip file, contains latest version
      - https://github.com/ESMValGroup/dummydata/archive/dev.zip
