---
# Notes on ncl-cdo-R packages relation for future releases:
# cdo=1.9.6 works only with ncl=6.6.2 but that
# implies the use of R packages from the r channel
# and those packages are R=3.2.2 << 3.5.1 and are
# obsolete (installing ncl=6.6.2 automatically removes
# the conda-forge-installed R (3.5.1) packages

name: esmvaltool
channels:
  - conda-forge
  # - r

dependencies:
  # Python packages that cannot be installed from PyPI:
  - iris
  - matplotlib<3  # Can be installed from PyPI, but is a dependency of iris and should be pinned.
  - python-stratify
  - esmpy
  - xarray  # Can be installed from PyPI, but here to get a consistent set of depencies with iris.
  # Non-Python dependencies
  - graphviz
  - cdo
  #- hdf5=1.10.4  # Pinned to help conda resolve the ncl/cdo combination

  # Multi language support:
  - ncl=6.4.0
  - jasper!=1.900.31  # pinned NCL dependency
  - r-base=3.4.1
  - libunwind  # Needed for Python3.7+
  # TODO: add julia
